name: capatcha
version: 0.1.2
author: icode <intelligentcodemail@gmail.com>
description: generate capatcha library
homepage: https://github.com/intelligentcode/capatcha
environment:
  sdk: '>=1.0.0 <2.0.0'
