name: captcha
version: 0.1.6
author: icode <intelligentcodemail@gmail.com>
description: generate captcha library
homepage: https://github.com/intelligentcode/captcha
environment:
  sdk: '>=1.0.0 <2.0.0'
